spring.application.name=serviceHub

server.port=8080

#Db Configurations
spring.datasource.url=jdbc:postgresql://${PG_URL}:5432/${DB_NAME}
spring.datasource.username=${PG_USERNAME}
spring.datasource.password=${PG_PWD}
spring.jpa.hibernate.ddl-auto=update

