spring.application.name=serviceHub

server.port=8080
server.address=0.0.0.0

#Db Configurations
spring.datasource.url=jdbc:postgresql://${PG_URL}:5432/${DB_NAME}
spring.datasource.username=${PG_USERNAME}
spring.datasource.password=${PG_PWD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

s3.bucket.name=${S3_BUCKET_NAME}
