spring.application.name=serviceHub

server.port=8080

#Db Configurations
spring.datasource.url=jdbc:postgresql://localhost:5432/serviceHub
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update

